global: 
  scrape_interval: 10s 
  evaluation_interval: 1s  

scrape_configs: 

  - job_name: 'prometheus' 
    scrape_interval: 5s 
    static_configs: 
    - targets: ['localhost:9090'] 

  - job_name: 'node' 
    ec2_sd_configs: 
      - region: us-east-1 
        port: 9100 

  - job_name: 'node_exporter' 
    static_configs: 
      - targets: ['localhost:9100'] 
