---
- name: Prometheus Installation
  hosts: localhost
  become: true
  become_method: sudo
  user: centos
  ignore_errors: yes
  tasks:
  - name: Update the system
    shell: "sudo yum update -y "
    
  - name: Add user
    shell: "sudo useradd --no-create-home --shell /bin/false prometheus"

  - name: Create a folder
    shell: "sudo mkdir /etc/prometheus"
    
  - name: Create folder
    shell: "sudo mkdir /var/lib/prometheus"

  - name: Change permission
    shell: "sudo chown prometheus:prometheus /etc/prometheus"

  - name: Change permission
    shell: "sudo chown prometheus:prometheus /var/lib/prometheus"
    

  - name: Install Prometheus
    shell:  "sudo wget https://github.com/prometheus/prometheus/releases/download/v2.3.2/prometheus-2.3.2.linux-amd64.tar.gz"
   

  - name: Unzip Prometheus 
    shell: "tar -xvf prometheus-2.3.2.linux-amd64.tar.gz"

  - name: Move the unziped files
    shell: "mv prometheus-2.3.2.linux-amd64 prometheus-files"



  - name: Copy binaries 
    command: "{{item}}"
    with_items:
    - sudo cp prometheus-files/prometheus /usr/local/bin/
    - sudo cp prometheus-files/promtool /usr/local/bin/
    - sudo chown prometheus:prometheus /usr/local/bin/prometheus
    - sudo chown prometheus:prometheus /usr/local/bin/promtool
    

  
  - name: Move console files
    command: "{{item}}"
    with_items:
    - sudo cp -r prometheus-files/consoles /etc/prometheus 
    - sudo cp -r prometheus-files/console_libraries /etc/prometheus 
    - sudo chown -R prometheus:prometheus /etc/prometheus/consoles 
    - sudo chown -R prometheus:prometheus /etc/prometheus/console_libraries 


  - name: Creates prometheus config file
    template:
      src: prometheus.yml
      dest: /etc/prometheus/prometheus.yml



  - name: Change permission
    shell: "sudo chown prometheus:prometheus /etc/prometheus/prometheus.yml"


  - name: Creates prometheus config file
    template:
      src: prometheus.service
      dest: /etc/systemd/system/prometheus.service


  - name:  Restarts
    command: "{{item}}"
    with_items:
    - sudo iptables -F
    - sudo systemctl daemon-reload 
    - sudo systemctl start prometheus 
    - sudo systemctl enable prometheus 
    - sudo systemctl status prometheus 
