---
- name: Node Exporter Installation
  hosts: localhost
  become: true
  become_method: sudo
  user: centos
  tasks:
    - name: Create repo
      template:
      src: grafana.repo
      dest: /etc/yum.repos.d/grafana.repo
      
    - name:
      shell: "sudo yum install grafana fontconfig freetype* urw-fonts -y"
      
    - name: Starts Grafana
      command: "{{item}}"
      with_items: 
      - sudo systemctl daemon-reload 
      - sudo systemctl start grafana-server 
      - sudo systemctl enable grafana-server.service 
      - sudo systemctl status grafana-server 
